### ISSUE TITLE
Feature request:

### ISSUE THREAD

**Issue by CaileanCarter** [aponsero/simple_parsers#1]
Hey Alise!

I have a parser for Metaphlan in Python you can add if interested: https://gist.github.com/CaileanCarter/8072901f73a012570455ac2cbfc6d486

Likewise, I have a parser for downloading fasta files from ENA from xml outputs: https://github.com/CaileanCarter/fasta_from_ena/tree/main

**Comment by aponsero** [comment]
Hello Hello!
These looks super convenient indeed, it would be good to add to the list! Sending you a collaborator invite so that you can add them/link them (however you feel is most convenient/relevant)!

**Comment by CaileanCarter** [comment]
Awesome, I've added them as submodules!
